#!/usr/bin/env php
<?php 
if(php_sapi_name() != 'cli') die('Restricted');
define('JKSTART', microtime(true));

require(__DIR__.'/func.php');
require(__DIR__.'/vendor/autoload.php');

$console = new Schedule(__DIR__.'/console.php');

$status  = $console->run(
 new JK\Console\IO\InputArgv,
 new JK\Console\IO\Output
);
exit($status);