#!/usr/bin/env php
<?php 
if(php_sapi_name() != 'cli') die('Restricted');
define('JKSTART', microtime(true));

require(__DIR__.'/func.php');
require(__DIR__.'/vendor/autoload.php');

$app = require(__DIR__.'/bootstrap/app.php');
$status  = $app->console->execute($argv[1]);
exit($status);