#!/usr/bin/env php
<?php 
if(php_sapi_name() != 'cli') die('Restricted');
define('JKSTART', microtime(true));

require(__DIR__.'/func.php');
require(__DIR__.'/vendor/autoload.php');

/*
$app = require(__DIR__.'/bootstrap/app.php');

$status  = $app->console->run(
 $input = new JK\Console\IO\InputArgv,
 new JK\Console\IO\Output
);
exit($status);
*/

$console = new Console(__DIR__.'/console.php');

$status  = $console->run(
 new JK\Console\IO\InputArgv,
 new JK\Console\IO\Output
);
exit($status);